### ISSUE TITLE
9 node image too small

### ISSUE THREAD

**Issue by dnnrly** [dnnrly/layli#19]
**Add the layli definition here**

```yaml
nodes:
    - id: a
      contents: Node 1
    - id: b
      contents: Node 2
    - id: c
      contents: Node 3
    - id: d
      contents: Node 5
    - id: f
      contents: Node 4
    - id: e
      contents: Node 6
    - id: g
      contents: Node 7
    - id: h
      contents: Node 8
    - id: i
      contents: Node 9

edges:
    - from: a
      to: b
    - from: b
      to: c
    - from: c
      to: d
    - from: d
      to: e
    - from: c
      to: e
    - from: e
      to: d
    - from: d
      to: f
    - from: f
      to: g
    - from: f
      to: h
    - from: g
      to: i

width: 7
height: 4

```

**Describe what is wrong with the image produced**

Instead of seeing 9 nodes, we only see 6 and the paths to those nodes are missing.

![9-nodes](https://github.com/dnnrly/layli/assets/4982174/02d3395b-45ee-4aff-b58e-b904ba971824)

**What did you expect to see?**

9 nodes with all of the specified paths drawn.

**Other information**

Command that you ran: `layli ./9-nodes.layli`

Version of layli used: v0.0.1
